installation:
  tree:
    windows:
      package_manager:
        name: chocolatey
        command: |
          powershell -NoProfile -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
        check: choco --version
      python:
        check: where python
        command: "choco install -y python313"
      node: 
        check: where node
        command: "choco install -y nodejs-lts"
      nvm: 
        check: where nvm
        command: "choco install -y nvm"
      postman:
        check: where postman
        command: "choco install -y postman"
      docker-desktop:
        check: where docker
        command: "choco install -y docker-desktop"
      rancher:
        check: where rancher
        command: "choco install -y rancher-desktop"
      git:
        check: where git
        command: "choco install -y git"
      gcloud:
        check: where gcloud
        command: "choco install -y gcloudsdk"
      onepassword:
        check: where 1password
        command: "choco install -y 1password"
      vscode:
        check: where code
        command: choco install -y vscode
        extensions:
          command: "code --install-extension"
          items:
            - ms-python.python
            - dbaeumer.vscode-eslint
            - esbenp.prettier-vscode
            - github.copilot
            - ms-vscode.vscode-typescript-next
            - msjsdiag.debugger-for-chrome
            - ms-vscode.react-native
      intellij:
        check: where idea64.exe
        command: choco install -y intellijidea-ultimate
        plugins:
          command: "idea64.exe installPlugins"
          items:
            - com.intellij.java
            - org.jetbrains.kotlin
            - com.intellij.database
            - Pythonid
            - JavaScriptLanguage
            - NodeJS
            - ReactNative
      datagrip:
        check: where datagrip64.exe
        command: choco install -y datagrip
    macos:
      package_manager:
        - name: homebrew
          command: |
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          check: brew --version
      languages:
        - name: python
          check: which python
          command: sh -c "brew install python@3.13"
        - name: node
          check: which node
          command: sh -c "brew install node"
        - name: nvm
          check: which nvm
          command: sh -c "brew install nvm"
        - name: npm
          check: which npm
          command: sh -c "brew install npm"
      api_testing:
        - name: postman
          check: which postman
          command: sh -c "brew install --cask postman"
      containers:
        - name: docker
          check: which docker
          command: sh -c "brew install --cask docker"
        - name: rancher
          check: which rancher
          command: sh -c "brew install rancher"
      version_control:
        - name: git
          check: which git
          command: sh -c "brew install git"
      cloud_tools:
        - name: gcloud
          check: which gcloud
          command: sh -c "brew install --cask google-cloud-sdk"
      security_tools:
        - name: 1password
          check: which 1password
          command: sh -c "brew install --cask 1password"
      editors:
        vscode:
          package: visual-studio-code
          check: which code
          command: brew install --cask visual-studio-code
          extensions:
            command: sh -c "code --install-extension"
            items:
              - ms-python.python
              - dbaeumer.vscode-eslint
              - esbenp.prettier-vscode
              - github.copilot
              - ms-vscode.vscode-typescript-next
              - msjsdiag.debugger-for-chrome
              - ms-vscode.react-native
        intellij:
          package: intellij-idea-ultimate
          check: which idea
          command: brew install --cask intellij-idea-ultimate
          plugins:
            command: sh -c "idea installPlugins"
            items:
              - com.intellij.java
              - org.jetbrains.kotlin
              - com.intellij.database
              - Pythonid
              - JavaScriptLanguage
              - NodeJS
              - ReactNative
        datagrip:
          package: datagrip
          check: which datagrip
          command: brew install --cask datagrip
